### ISSUE TITLE
Skaffold file always required

### ISSUE THREAD

**Issue by nicosuave** [google-github-actions/create-cloud-deploy-release#38]
### TL;DR

Per the documentation, it seemed that I can omit a `skaffold.yml` if providing `images`, however am seeing the following (and have confirmed the value for `images` is being properly passed to the CLI call):

```
ERROR: (gcloud.deploy.releases.create) Could not find skaffold file. File [./skaffold.yaml] does not exist
```

### Expected behavior

`gcloud deploy releases create --help` insinuates `images` should be enough?

### Action YAML

```yaml
with:
  delivery_pipeline: ...
  name: ...
  region: ...
  description: ...
  images: ...
```
